name: mine_matrix
description: "Mine Matrix - Mining App"
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0   # API calls optional

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon.png

# =========================
# Flutter Launcher Icons
# =========================
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: false   # Map structure, boolean নয়
# =========================
# Flutter Native Splash
# =========================
flutter_native_splash:
  color: "#ffffff"               # background color
  image: assets/icon/app_icon.png
  android: true
  ios: true
  web: false                    # web splash handled separately
  android_gravity: center
  ios_content_mode: scaleAspectFit
